# Linux Firewall Configuration

# Default policies
default_policies:
  input: DROP
  forward: DROP
  output: ACCEPT

# Custom rules
rules:
  # Allow SSH access
  - chain: INPUT
    protocol: tcp
    port: 22
    action: ACCEPT
    comment: "Allow SSH access"

  # Allow HTTP and HTTPS
  - chain: INPUT
    protocol: tcp
    port: 80
    action: ACCEPT
    comment: "Allow HTTP"
  
  - chain: INPUT
    protocol: tcp
    port: 443
    action: ACCEPT
    comment: "Allow HTTPS"

  # Allow DNS queries
  - chain: INPUT
    protocol: udp
    port: 53
    action: ACCEPT
    comment: "Allow DNS queries"

  # Allow ICMP (ping)
  - chain: INPUT
    protocol: icmp
    action: ACCEPT
    comment: "Allow ICMP"

  # Allow NTP
  - chain: INPUT
    protocol: udp
    port: 123
    action: ACCEPT
    comment: "Allow NTP"

# Logging configuration
logging:
  level: INFO
  file: /var/log/firewall.log
  max_size: 10485760  # 10MB
  backup_count: 5 